### PR TITLE
fix: escape JSON breaking characters in PagerDuty request body

### LINKED ISSUE #22: Alerts sent via PagerDuty fails if the body contains JSON breaking characters

### PR DESCRIPTION
**Pull request by amgadramses**
Fixes #22

### CODE REVIEW

File: provider/pagerduty.go [hunk 1]
```diff
@@ -116,3 +117,14 @@ func buildRequestBody(ev *event.Event, key string) string {
 
 	return reqBody
 }
+
+func JsonEscape(i string) string {
+	jm, err := json.Marshal(i)
```
Comment (abahmed) [inline provider/pagerduty.go:122]: I think we need to check string length here

**Review by abahmed — APPROVED** [review]
